version: "3.5"

services:
  postgres:
    image: postgres:16
    user: ${RUNAS_UID}:${RUNAS_GID}
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "log_statement=all"]
  
  redis:
    image: redis:7-alpine
    user: ${RUNAS_UID}:${RUNAS_GID}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data